language: cpp
sudo: true

dist: trusty

git:
  depth: 1

addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
    packages:
      - libz-dev

env:
    - LLVM=3.8
    - LLVM=4.0
    - LLVM=5.0

compiler:
    - 'clang++'
    - 'g++'
    - 'g++-5'

install:
  - git clone --depth 1 https://github.com/tomsik68/travis-llvm.git
  - cd travis-llvm
  - chmod +x travis-llvm.sh
  - ./travis-llvm.sh ${LLVM}
  - cd ..

script:
  # gcc in the versions that we use has problems with sanitizers
  - if test "$CXX" = "clang++"; then export CXX_FLAGS="-fsanitize=undefined,address"; fi
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_CXX_FLAGS=$CXX_FLAGS .
  - make -j2
  - cd tests
  - make
  # for now turn off the detection of leaks, we're working on it
  - ASAN_OPTIONS=detect_leaks=0 make check

notifications:
    email: false
